


update:
	wget -O js/xterm.min.js https://cdn.bootcss.com/xterm/3.12.0/xterm.min.js
	wget -O css/xterm.min.css https://cdn.bootcss.com/xterm/3.12.0/xterm.min.css
	wget -O js/fit.min.js https://cdn.bootcss.com/xterm/3.12.0/addons/fit/fit.min.js
	wget -O js/attach.min.js https://cdn.bootcss.com/xterm/3.12.0/addons/attach/attach.min.js
	wget -O js/winptyCompat.min.js https://cdn.bootcss.com/xterm/3.12.2/addons/winptyCompat/winptyCompat.min.js
	wget -O js/webLinks.min.js https://cdn.bootcss.com/xterm/3.12.2/addons/webLinks/webLinks.min.js